### PR TITLE
feat: Add pop support panel

### PR DESCRIPTION
**Pull request by mmstick**
Requires https://github.com/pop-os/support-panel to be released with it.

Screenshot from 2022-01-21 22-05-25

### CODE REVIEW

**Comment by 13r0ck** [comment]
Should this say "Create log archives for *Professional support*"? The logs might be useful in community support too

**Comment by mmstick** [comment]
I currently have these two sections hidden when the system is not of System76 origin, but we could alter their descriptions and functions for community support in some way.

**Comment by mmstick** [comment]
Chopped `Professional` from that sentence and am not hiding it, so they could use it for community support / issue reports.

**Comment by jacobgkau** [comment]
It looks like the build failed on the build server for 7c5533d, but it does build locally.

Should `libpop-support-panel` and/or `libpop-support-panel-dev` be added to debian/control as a depends/build-depends?

**Comment by mmstick** [comment]
Yeah, they should

**Comment by jacobgkau** [comment]
This panel is currently not able to scroll vertically, so it has a rather large minimum height:

Screenshot from 2022-01-24 14-35-57

It doesn't do well with tilling (doesn't quarter-tile on a 1080p display). Can the page be vertically scrollable?

**Comment by jacobgkau** [comment]
It also looks like the log file functionality isn't working yet. When I click `Create Log Files`, I get a line of output in the terminal/journalctl that says `[src/lib.rs:336] &output = ""`, and the `Create Log Files` dialog with the `Show in Folder` button goes away as soon as I enter my password.

**Comment by mmstick** [comment]
I'll add vertical scrolling and check if the pop-support binary is in the package.

**Comment by mmstick** [comment]
I've wrapped the panel in a `ScrolledWindow`. I've also checked that support log generation functions. Should work as long as `libpop-support-panel` is `24af463`.

**Comment by jacobgkau** [comment]
Still not seeing logs work:
```
system76@pop-os:~$ apt policy gnome-control-center libpop-support-panel
gnome-control-center:
  Installed: 1:40.0-1ubuntu5pop0~1643064721~21.10~48009d4
  Candidate: 1:40.0-1ubuntu5pop0~1643064721~21.10~48009d4
  Version table:
 *** 1:40.0-1ubuntu5pop0~1643064721~21.10~48009d4 1002
       1002 http://apt.pop-os.org/staging/support impish/main amd64 Packages
        100 /var/lib/dpkg/status
     1:40.0-1ubuntu5pop0~1637613403~21.10~2dafb76 1002
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1002 http://apt.pop-os.org/staging/master impish/main amd64 Packages
     1:40.0-1ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu impish/main amd64 Packages
libpop-support-panel:
  Installed: 1.0.0~1643064738~21.10~24af463
  Candidate: 1.0.0~1643064738~21.10~24af463
  Version table:
 *** 1.0.0~1643064738~21.10~24af463 1002
       1002 http://apt.pop-os.org/staging/master impish/main amd64 Packages
        100 /var/lib/dpkg/status
system76@pop-os:~$ 
```

Here is `sudo journalctl -f` when I try to create logs:
```
Jan 24 16:32:39 pop-os gnome-shell[3094]: polkitAuthenticationAgent: Received 2 identities that can be used for authentication. Only considering one.
Jan 24 16:32:42 pop-os polkitd(authority=local)[1043]: Operator of unix-session:2 successfully authenticated as unix-user:system76 to gain ONE-SHOT authorization for action org.pop.support.generate-logs for unix-process:61733:1536201 [gnome-control-center] (owned by unix-user:system76)
Jan 24 16:32:42 pop-os pkexec[61773]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
Jan 24 16:32:42 pop-os pkexec[61773]: system76: Executing command [USER=root] [TTY=unknown] [CWD=/home/system76] [COMMAND=/usr/bin/pop-support generate-logs]
Jan 24 16:32:42 pop-os gnome-control-center.desktop[61733]: [src/lib.rs:342] &output = ""
```

This is what I see when I try to run `pop-support` manually:
```
system76@pop-os:~$ pop-support generate-logs
fetching output from `dmidecode `
fetching output from `lspci -vv`
fetching output from `lsusb -vv`
fetching output from `dmesg `
fetching output from `journalctl --since yesterday`
fetching output from `upower -d`
copying logs from /var/log/apt/history.log
copying logs from /var/log/Xorg.0.log
copying logs from /var/log/syslog
dmidecode exited in failure

Caused by:
    status is unknown: exit status: 1
system76@pop-os:~$ sudo pop-support generate-logs
fetching output from `dmidecode `
fetching output from `lspci -vv`
fetching output from `lsusb -vv`
fetching output from `dmesg `
fetching output from `journalctl --since yesterday`
fetching output from `upower -d`
copying logs from /var/log/apt/history.log
copying logs from /var/log/Xorg.0.log
copying logs from /var/log/syslog
failed to open source

Caused by:
    No such file or directory (os error 2)
system76@pop-os:~$ 
```

**Comment by mmstick** [comment]
I see. Some logs may be missing

**Comment by mmstick** [comment]
Okay, `d6393b1` should be ignoring errors when fetching missing logs around the system, and compressing the logs that it did find successfully.

**Comment by mmstick** [comment]
It appears to running an older version of the pop-support binary somehow.

I've added extra logs. If one of those errors occurs, it should print this instead:

```
copying logs from /var/log/Xorg.0.log
copying logs from /var/log/syslog
[src/system76.rs:22] futures::join!(dmidecode(tempfile(temppath, "dmidecode") ?),
               lspci(tempfile(temppath, "lspci") ?),
               lsusb(tempfile(temppath, "lsusb") ?),
               dmesg(tempfile(temppath, "dmesg") ?),
               journalctl(tempfile(temppath, "journalctl") ?),
               upower(tempfile(temppath, "upower") ?),
               copy(Path :: new("/var/log/apt/history.log"), apt_history),
               copy(Path :: new("/var/log/Xorg.0.log"), xorg_log),
               copy(Path :: new("/var/log/syslog"), syslog),) = (
    Ok(
        (),
    ),
    Ok(
        (),
    ),
    Ok(
        (),
    ),
    Ok(
        (),
    ),
    Ok(
        (),
    ),
    Ok(
        (),
    ),
    Ok(
        (),
    ),
    Err(
        Error {
            context: "failed to open source",
            source: Os {
                code: 2,
                kind: NotFound,
                message: "No such file or directory",
            },
        },
    ),
    Err(
        Error {
            context: "failed to open source",
            source: Os {
                code: 2,
                kind: NotFound,
                message: "No such file or directory",
            },
        },
    ),
)
logs generated: ["lspci", "dmesg", "syslog", "upower", "journalctl", "Xorg.0.log", "dmidecode", "apt_history", "lsusb"]
PATH /tmp/pop-support/system76-logs.tar.xz
```

**Comment by jacobgkau** [comment]
Log gathering is working now. The change from logs being placed in the home directory to `/tmp/pop-support` is significant and should be communicated to the support team.

Are the logs supposed to be less inclusive than they were before? I see the following differences:

- system76-driver includes `/etc/apt/sources.list{,.d/*}` and `/var/log/apt/term` in addition to `/var/log/apt/history.log`; pop-support includes only `/var/log/apt/history.log`.
    - The apt sources were added to assist with upgrade troubleshooting.
- system76-driver includes the output of `df -h` and `lsblk`, pop-support does not.
    - This would be used to assist users having free space or extra drive mounting issues.
- system76-driver includes `/etc/fstab`, pop-support does not.
    - This is used for both upgrade troubleshooting and drive mounting issues.
- system76-driver includes the output of `sensors`, pop-support does not.
    - I believe this one was [intended](https://github.com/pop-os/system76-driver/pull/192) to help confirm temperature/fan speed reports.
- system76-driver includes `systeminfo.txt` which includes the model of computer, OS version, and kernel version.
    - While it's possible to get this information from other sources (dmidecode, apt history, and dmesg), having it in one location makes it much quicker to easily see an overview of the customer's system. I know I used this one a lot to confirm quickly if the user's on Pop!_OS or Ubuntu, on LTS or not, on an unsupported/EOL release, etc.
- system76-driver includes the output of `uptime`, pop-support does not.
    - This one was used to detect when a user hasn't rebooted in a thousand years.
- pop-support includes `upower` while system76-driver does not; this one's fine.

A loading spinner on the "Create Log Files" dialog would also be nice while the files are being gathered; I thought it had frozen the first time I ran it.

It also looks like the log archive is overridden each time log files are generated. These should really be generated in addition and not overridden; a user clicking the button more times than needed (or more times than they've been asked to) could easily destroy important information if logs have already been rotated, etc.

**Comment by mmstick** [comment]
Just my poor knowledge on what the former was collecting. I will add these

**Comment by mmstick** [comment]
I guess we can have multiple logs. Was just worried about potential leaking of sensitive info.

**Comment by jacobgkau** [comment]
> I guess we can have multiple logs. Was just worried about potential leaking of sensitive info.

Was there a reason the location they're saved in has changed? I don't want to say they should be in the same place just because that's how it was before, but if you're worried about collecting more info than a user's expecting over time, being in the home directory makes it less easy to forget that they're there, and also generally keeps them organized by the user who generated them.

(The home directory is also usually easier to get to in a file picker than /tmp, especially on GNOME where a user needs to click "Other Locations," "Computer" to get to the root directory; the home directory's usually pinned, if not the default folder that's shown.)

**Comment by mmstick** [comment]
I placed it in `/tmp` so it gets automatically destroyed on a reboot / power loss, and when the dialog opens the folder where it resides it'd be the only file in that folder. But I can place it in `/home`.

**Comment by WatchMkr** [comment]
We'd like to keep them the logs in /home so it's easy for users to find and attach. There should be a dialog confirming the logs were created and their location along with a button to open /home.

**Comment by mmstick** [comment]
As of `b8b5368`, all the requested logs are now generated, and the log is placed in the home folder requested by the call of the pop-support binary.

**Comment by jacobgkau** [comment]
gnome-control-center is crashing on launch with libpop-support-panel b8b5368:
```
system76@pop-os:~$ gnome-control-center 
../src/intel/isl/isl.c:2095: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /build/pop-support-panel-ufoIoD/pop-support-panel-1.0.0~1643144951~21.10~b8b5368/vendor/tokio/src/runtime/context.rs:21:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by mmstick** [comment]
I'll fix that in a minute.

**Comment by mmstick** [comment]
With `753640f` I have switched from tokio to smol for the async runtime. I've verified that it works inside GNOME Settings and successfully generates the log. Unsure if there's a good way to activate tokio's reactor from a C application.

**Comment by jacobgkau** [comment]
The apt directory in the log archive does not include `sources.list.d`, only the (empty by default) `sources.list`. Also, `systeminfo.txt` is empty. The rest of the logs look good-- I noticed that stderr (which was introduced semi-intentionally with https://github.com/pop-os/system76-driver/pull/192) is no longer included in the logs, but the stderr output is minimal and probably not as important.

Looking at the design again, when the page becomes scrollable, there is no bottom margin below the last row, which makes it difficult to determine if I'm actually at the bottom:
Screenshot from 2022-01-26 12-39-30
Compare this to the About page:
Screenshot from 2022-01-26 12-39-43
A bottom margin like the About page has would be nice. Also, the minimum width is a little large, with a lot of empty space in the middle:
Screenshot from 2022-01-26 12-40-00
The About page gets skinnier:
Screenshot from 2022-01-26 12-40-09
Being able to collapse horizontally a little more would also be nice.

**Comment by mmstick** [comment]
We should be good with `5b0f864`. It's now generating the missing logs. Added a bottom margin so it can scroll past the end of the list. And the minimum width has been reduced.

Screenshot from 2022-01-27 22-29-32

**Comment by jacobgkau** [comment]
Logs look good now. Minimum size is also looking great. At the default window size, the width of the rows is noticeably skinnier than any of the other pages, and is skinnier than the mockups indicate:

Screenshot from 2022-01-27 15-40-36
Screenshot from 2022-01-27 15-40-48
Screenshot from 2022-01-27 15-40-44
Screenshot from 2022-01-27 15-40-52

Any way to expand the rows' maximum width to match the other pages when possible, but still allow it to shrink the way it currently does?

**Comment by mmstick** [comment]
Found a way to do this with `449cead`

**Comment by jacobgkau** [comment]
Width is as expected now, still collapseable, and height is also still collapseable. Documentation, Pop!_Chat, and Support buttons are all working on a System76 system. Logs are created in the home directory (now with a timestamp in a `.tar.xz` file extension, which is a great improvement).

The button to show logs in their folder works to open the home directory, but the log file is not pre-selected. I can make Nautilus open with the file pre-selected by running e.g. `nautilus --select /home/system76/pop-support_1643409456.tar.xz`. Can the button in the dialog do that? It would be helpful when the Nautilus window opens at a small size and/or there are many other files in the home directory.

**Comment by mmstick** [comment]
Yeah, sure.

**Comment by mmstick** [comment]
`903ea5c` will use that command

**Comment by jacobgkau** [comment]
Oh, I just meant opening it so the file's selected, not necessarily using that command. Although `nautilus` is a dependency of `pop-desktop`, so it should be safe for us to depend on it, and it doesn't look like `xdg-open` supports doing this.

In a virtual machine (non-System76 system), confirmed that the `Professional Support` line does not show up. However, the Pop!_OS logo seems to be scaled wrong:

image

I noticed the System76 logo is being shown at a 1:1 scale with its PNG file, so I also want to take a look on a HiDPI system to make sure the logo scales properly before this is approved.

**Comment by mmstick** [comment]
The pixel size isn't being set, so I'll fix that.

**Comment by mmstick** [comment]
https://github.com/pop-os/support-panel/commit/eb633a7ea411cd4c2099bb1c42114804d06fa6cb

I've checked that they both scale with `env GDK_SCALE=2 cargo run -- gtk`. But the quality of the System76 logo is a bit iffy on a LoDPI screen scaled up. If you know where I can get a SVG, that could be dropped in as a replacement in the gresource.xml file.

**Comment by 13r0ck** [comment]
Pop svg: 
https://github.com/system76/brand/blob/master/Pop_OS%20branding/Pop_icon.svg

System76 svg: 
https://github.com/system76/brand/blob/master/System76%20branding/system76-logo_secondary.svg

**Comment by jacobgkau** [comment]
It's not as ridiculously small now, but the virtual machine still has more padding than it should around the Pop!_OS logo on this page:

image

Comparing https://github.com/pop-os/support-panel/blob/f6ffaa576a6bd60268c88482fa7c017291c1e6be/data/system76.svg and https://github.com/pop-os/support-panel/blob/f6ffaa576a6bd60268c88482fa7c017291c1e6be/data/pop.svg, the Pop!_OS logo has a lot more horizontal padding; maybe the SVGs need to be on similarly sized canvases.

**Comment by mmstick** [comment]
Do we have a SVG that doesn't have the padding built in?

**Comment by mmstick** [comment]
Maybe setting the height and avoiding setting a width will help

**Comment by jacobgkau** [comment]
> Do we have a SVG that doesn't have the padding built in?

Here are the files currently being used after removing the padding in Inkscape (Ctrl-Shift-R):

- [system76.svg](https://user-images.githubusercontent.com/7199422/152001269-3ab219ae-ac31-4cb7-b638-3cc84b1c3a0a.svg)
- [Pop_icon.svg](https://user-images.githubusercontent.com/7199422/152001267-b0930a55-96d7-4082-b859-7d6a0fd3c9b3.svg)

**Comment by mmstick** [comment]
Okay. I've replaced the SVGs with these in the last commit to pop-support-panel

**Comment by jacobgkau** [comment]
Logo size is looking good on both physical and VM now:

image

There's still no loading spinner while creating log files:

Screenshot from 2022-02-01 10-07-27

I see the mockup doesn't have a spinner:

image

@maria-komarova / @WatchMkr just making sure there's not supposed to be a spinner here? It does take a few seconds and the entire window is frozen while that's happening, so some indication of progress/activity seems like it might improve the experience.

**Comment by maria-komarova** [comment]
I think it might be a good idea to have a spinner to the left of "Creating Files..."  I can adjust the mockup for that a little later if needed.

**Comment by mmstick** [comment]
Added spinner https://github.com/pop-os/support-panel/commit/65c076c020d4d4d31486e45350ccac37952acb43

**Comment by jacobgkau** [comment]
The spinner looks good:
Screenshot from 2022-02-01 12-22-55
Looking at this dialog a little closer, the rounded corners from the mockup aren't there, and there's a tiny amount of space between the buttons and the left/bottom/right edges of the dialog that isn't there in the mockup. Can those things be tweaked any further, or is this as close as it can get?

**Comment by maria-komarova** [comment]
As long as the styling is consistent with other confirmation dialogs of this kind, it should be fine.

**Comment by jacobgkau** [comment]
> As long as the styling is consistent with other confirmation dialogs of this kind, it should be fine.

Confirmation dialogs in Nautilus don't have much of a corner radius, but they do have the buttons extending all the way to the edges:
Screenshot from 2022-02-01 12-33-48

The Pop Shell floating window exception dialog looks a little more similar to the mockup, with a larger corner radius:
Screenshot from 2022-02-01 12-34-01

I don't know anywhere else that the buttons have that sliver of margin around them on the edges of the window.

**Comment by maria-komarova** [comment]
We should probably follow the Nautilus one

**Comment by mmstick** [comment]
https://github.com/pop-os/support-panel/commit/ff1b1c741b93b8a0005f6bb9095e3697778c2fa5

Required using a MessageDialog and tossing out the bits that we aren't using. Couldn't find any padding or borders being added by themes or by the widget itself.

**Comment by jacobgkau** [comment]
Hmm, maybe that wasn't the best idea... now there's no border around the top of the dialog, so it's not distinguishable from the window in the background:

Screenshot from 2022-02-02 09-19-25

(There's also a a tiny black triangle in each of the bottom corners filling in where they would otherwise be rounded. If you click the screenshot to view it in its own tab, they show up white, so they're easier to see.) If I drag the Nautilus dialog over the window, it doesn't have those problems:

Screenshot from 2022-02-02 09-20-04

We need at least some border/shadow around the entire dialog.

**Comment by mmstick** [comment]
Sounds like custom CSS is required to do what our theme isn't.

**Comment by mmstick** [comment]
Forgot to mention but the issue was that I had set `decoration(false)`. The window decorations are working now.

**Comment by jacobgkau** [comment]
Ok, that dialog's looking much more normal:

Screenshot from 2022-02-03 09-23-16
Screenshot from 2022-02-03 09-23-22

Padding looks a little tight on the left/right of the sentence (compared to how much space is above the header/below the sentence), I don't know if that's just me.

One more thing I noticed while going back to double-check other functionality is that when resizing the window (with keyboard or mouse), the collapsible left sidebar starts flickering when the panel contents starts shrinking:

https://user-images.githubusercontent.com/7199422/152385322-9d58defd-d2cd-4dc5-b19d-afd36217bd59.mp4

I can't recreate this with e.g. the About panel.

**Comment by mmstick** [comment]
@jacobgkau Padding issues, and the left panel collisions, should be fixed now

**Comment by jacobgkau** [comment]
Padding looks better, the flickering issue is fixed.

The `Create Log Files` button works on System76 hardware, but in a virtual machine, it doesn't show the success dialog after I enter my password (and logs are not created.) I get `[src/lib.rs:309] &output = ""` in a terminal (where the output string is supposed to be the path to the log file), and when I try running `pop-support generate-logs /home/system76` manually, the command returns immediately with no output (not seeing any other logs in journalctl while doing this.)

**Comment by mmstick** [comment]
Does `/sys/devices/virtual/dmi/id/sys_vendor` exists in that VM? Maybe that's why

**Comment by mmstick** [comment]
Actually, I see that it's because it defaults to doing nothing if the vendor isn't System76.

**Comment by mmstick** [comment]
Commit `53ae5a7` will enable support for log generation for all vendors.

**Review by jacobgkau — APPROVED** [review]
Log creation works in the VM now.

I took another look through all features on hardware (System76) and VM (non-System76). Design matches what's been discussed and is in line with similar panels. All buttons are working. Logs created with pop-support (or the GUI button) include all information that system76-driver currently includes, with the addition of upower output and more detailed kernel version information.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
