### PR TITLE
improv: Use proper subpanels for "Desktop", like "Privacy"

### PR DESCRIPTION
**Pull request by ids1024**
Currently this is a bit funny, since the subpanels are missing icons. We'll either need icons for each of these, or need to find a way to work around that requirement:

Screenshot from 2022-03-01 14-00-05

We'll also need to verify that searches are working as expected, and make any other necessary changes to the `.desktop` files.

Fix for https://github.com/pop-os/gnome-control-center/issues/174.

Requires https://github.com/pop-os/desktop-widget/pull/83.

### CODE REVIEW

**Comment by maria-komarova** [comment]
For Desktop Options (now General, to be renamed) we can use "video-display-symbolic" icon and "video-display" for the color icon. It is an existing icon that I am not aware is used anywhere else. Let me know if it is actually used somewhere. 
For Background, use "preferences-desktop-wallpaper-symbolic" and "preferences-desktop-wallpaper" respectively.

### New icons (including svgs and pngs below):

#### 1. "preferences-desktop-appearance-symbolic" and "preferences-desktop-appearance". 
preferences-desktop-appearance-symbolic
preferences-desktop-appearance
preferences-desktop-appearance-256
preferences-desktop-appearance-256
preferences-desktop-appearance-128
preferences-desktop-appearance-64
preferences-desktop-appearance-48
preferences-desktop-appearance-32
preferences-desktop-appearance-24
preferences-desktop-appearance-16


#### 2. "preferences-desktop-dock-symbolic" and "preferences-desktop-dock".
preferences-desktop-dock-symbolic
preferences-desktop-dock
preferences-desktop-dock-256
preferences-desktop-dock-128
preferences-desktop-dock-64
preferences-desktop-dock-48
preferences-desktop-dock-32
preferences-desktop-dock-24
preferences-desktop-dock-16


#### 3. "preferences-desktop-workspaces-symbolic" and "preferences-desktop-workspaces"
preferences-desktop-workspaces-symbolic
preferences-desktop-workspaces
preferences-desktop-workspaces-256
preferences-desktop-workspaces-128
preferences-desktop-workspaces-64
preferences-desktop-workspaces-48
preferences-desktop-workspaces-32
preferences-desktop-workspaces-24
preferences-desktop-workspaces-16

**Comment by ids1024** [comment]
The symbolic appearance icon seems to end up monochrome, losing the intermediate shade of grey. I'm not really sure how this differs from the background icon that seems to have a couple shades of grey.

Screenshot from 2022-03-14 12-30-45

Is there any particular way the pngs here were generated from the svg? Pop-icons uses a script for that. The centering could probably be better:

Screenshot from 2022-03-14 13-10-27

I guess icons should either have 2x and 3x hiDPI versions, or maybe we should export the variants as svgs like in https://github.com/pop-os/icon-theme/pull/103.

**Comment by maria-komarova** [comment]
I can export them as separate svgs for sure. Centering was done using a template that we have to ensure they are centered similar to other icons of the similar kind. For example, video-display icon.

**Comment by maria-komarova** [comment]
Let's see if this version would work better for a symbolic icon. 
preferences-desktop-appearance-symbolic

**Comment by maria-komarova** [comment]
Below are SVGs of the new icons.
1. Appearance
preferences-desktop-appearance-16
preferences-desktop-appearance-24
preferences-desktop-appearance-32
preferences-desktop-appearance-48
preferences-desktop-appearance-64
preferences-desktop-appearance-128
preferences-desktop-appearance-256

2. Dock
preferences-desktop-dock-16
preferences-desktop-dock-24
preferences-desktop-dock-32
preferences-desktop-dock-48
preferences-desktop-dock-64
preferences-desktop-dock-128
preferences-desktop-dock-256

3. Workspaces
preferences-desktop-workspaces-16
preferences-desktop-workspaces-24
preferences-desktop-workspaces-32
preferences-desktop-workspaces-48
preferences-desktop-workspaces-64
preferences-desktop-workspaces-128
preferences-desktop-workspaces-256

**Comment by ids1024** [comment]
Hm, it seems like adding icons here to the `hicolor` theme  (as is normally done for app icons) doesn't show them correctly in the launcher, since `st_icon_set_icon_name` seems to favor `preferences-desktop` from the current icon theme (`Pop`), over `preferences-desktop-appearance` from the fallback (`hicolor`).

Not sure the best solution; could just name the icons differently.

**Comment by ids1024** [comment]
Updated `.desktop` file `Comment=` fields to what was in desktop-widget. This and https://github.com/pop-os/desktop-widget/pull/86 are ready for review now.

**Review by jackpot51 — APPROVED** [review]

**Review by leviport — APPROVED** [review]
Works great!

**Pull request merged**
