### PR TITLE
Uses @theme_fg_color for the drag handles instead of @borders

### LINKED ISSUE #366: 19.10: Grab handles for rearranging list items are low contrast
**Describe the problem:**
The six-dot grabbing areas on the left sides of list items are low contrast in light and dark modes.

g-c-c-low-contrast-grabbers
g-c-c-low-contrast-grabbers-dark

**Steps to reproduce:**
A good example of these grabbers is in gnome-control-center in the "Search" category.

**Distribution:**
Pop!_OS 19.10

**Pop version:**
```
system76@pop-os:~$ apt policy pop-gtk-theme 
pop-gtk-theme:
  Installed: 5.0.0~1570998216~19.10~cbbf790
  Candidate: 5.0.0~1570998216~19.10~cbbf790
  Version table:
 *** 5.0.0~1570998216~19.10~cbbf790 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status
```

### PR DESCRIPTION
**Pull request by isantop**
See https://gitlab.gnome.org/GNOME/gnome-control-center/merge_requests/597

Fixes pop-os/gtk-theme#366

### CODE REVIEW

**Comment by isantop** [comment]
I can't seem to request a review from @pop-os/engineering

**Review by mmstick — APPROVED** [review]

**Comment by brs17** [comment]
Is this supposed to be going into master_disco?

**Comment by jackpot51** [comment]
@isantop this looks like it is based on master_disco

**Comment by isantop** [comment]
I will rebase the PR on master_eoan and resubmit

**Pull request closed without merging**
