### PR TITLE
Rebase to 3.38.6

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by crawfxrd — APPROVED** [review]

**Review by jacobgkau — CHANGES_REQUESTED** [review]
With this branch, the `Search` page is present and I'm able to enable file searching through the Applications menu. That would be a regression in the scope of our currently expected features.

**Comment by bflanagin** [comment]
I'm not sure if this is expected, but the Cosmic Desktop options are no longer visible after the rebase as well.

**Comment by jacobgkau** [comment]
There's a new `Power Mode` section on the Power page.

Screenshot from 2021-07-28 15-49-23

This looks like it should correspond to system76-power profiles, but it doesn't. Do we want to do anything with that (connect it to system76-power or remove it)?

**Comment by mmstick** [comment]
We can remove it for now

**Comment by ids1024** [comment]
This has reverted the Keyboard panel to the stock 3.38 version.

**Comment by ids1024** [comment]
There were also changes to the Region panel along with the changes to the Keyboard panel (like moving input sources from there to the keyboard panel).

(It's a bit of a mess, but those changes are mostly upstream in Gnome 40+.)

**Comment by jacobgkau** [comment]
> There were also changes to the Region panel along with the changes to the Keyboard panel (like moving input sources from there to the keyboard panel).

Can confirm, input sources are currently in both the Keyboard and Region panels (shouldn't be in the Region panel.)

**Review by jacobgkau — CHANGES_REQUESTED** [review]
The `Manage Installed Languages` button is now missing on the Region & Language page.

**Comment by jacobgkau** [comment]
The last commit commented out `0011-region-Add-Language-Selector-button.patch`, which appears to be what adds the `Manage Installed Languages` button.

**Comment by jacobgkau** [comment]
The build failed. Testing locally, the patch wasn't applying. Looking at https://github.com/pop-os/gnome-control-center/commit/3bbd03d213a291c8b38dc026b9bdb26509898096 as an example, I updated and refreshed the patch and it now appears to be working. Testing will resume once this builds on the build server again.

**Review by jacobgkau — APPROVED** [review]
Not seeing any more issues. Regression testing has passed: [gcc-testing-pr190.txt](https://github.com/pop-os/gnome-control-center/files/6947260/gcc-testing-pr190.txt)

**Pull request merged**
