### PR TITLE
Rename 'search' to 'activate-launcher', matching change in pop shell, fixing #93

### LINKED ISSUE #93: Shortcut for launcher (Super + /) not visible in list of shortcuts in settings
**Distribution (run `cat /etc/os-release`):**

```
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 0.1.0~1588274983~20.04~586efcc
  Candidate: 0.1.0~1588274983~20.04~586efcc
  Version table:
 *** 0.1.0~1588274983~20.04~586efcc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status

```

**Issue/Bug Description:**

In settings, under the section "Navigate applications and windows" in the keyboard shortcuts list there is supposed to be an option to change the shortcut to the launcher. For me and for some other user I've seen on reddit, that option isn't there.

Screenshot from 2020-05-01 23-15-36

**Steps to reproduce (if you know):**

\-

**Expected behavior:**

For the shortcut to be there and editable.

**Other Notes:**

I have a nordic layout keyboard so the default Super + /  command is a no-go since / is typed with the key combo shift + 7 (i think many european keyboard layouts do this). Also, I'm unsure if it matters but I did upgrade to 20.04 from 19.10 rather than doing a clean install.

### PR DESCRIPTION
**Pull request by ids1024**
Depends on https://github.com/pop-os/shell/pull/436. Fixes #93.

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Review by leviport — APPROVED** [review]
Approved after code review

**Comment by leviport** [comment]
Note: since https://github.com/pop-os/shell/pull/436 is merging into `dev`, make sure this does not get merged until `dev` is merged.

**Comment by ids1024** [comment]
> Note: since [pop-os/shell#436](https://github.com/pop-os/shell/pull/436) is merging into `dev`, make sure this does not get merged until `dev` is merged.

I originally filed both PRs against master. @mmstick changed the base branch for that PR, but not this one.

@mmstick Was that intentional, for some reason I can't think of, or did you mean to change both?

**Comment by ids1024** [comment]
Okay, I guess I see. Pop-shell is being developed on `dev` with regular rollup merges into `master`.

**Comment by leviport** [comment]
I would be okay with exempting these two PRs from the `dev` branch process, but I will defer to engineering about whether or not that's a good idea.

Edit: Looks like https://github.com/pop-os/shell/pull/436 was already merged into `dev`. That's alright, we can just make a note to merge this when we merge `dev`.

**Comment by mmstick** [comment]
I merged dev, so we can merge this if QA is okay with it

**Comment by leviport** [comment]
`dev` with https://github.com/pop-os/shell/pull/436 was already merged? That PR was merged into `dev` less than 10 minutes ago.

As soon as https://github.com/pop-os/shell/pull/436 is in master, I'm okay with merging this.

**Pull request merged**
