### PR TITLE
feat(desktop): Set sidebar to visible child

### LINKED ISSUE #174: Make panels under "Desktop" directly searchable
This enables users to type "Dock" in the launcher and get the correct result. The Privacy panel has this setup for its sub-panels.

### PR DESCRIPTION
**Pull request by mmstick**
Closes #174

### CODE REVIEW

**Comment by bflanagin** [comment]
@mmstick It looks like this PR only fixes one sub-panel (Backgrounds) in the Desktop settings. From what I understand #174 wouldn't be closed as it refers to "Dock" directly and all other sub-panels indirectly. It does fix https://github.com/pop-os/beta/issues/152, but I'm not sure if that is intended.

**Comment by jacobgkau** [comment]
@bflanagin Not sure if this is what you mean, but I see that searching _within_ Settings, all five sub-pages return `Desktop` as a result, while the Privacy panel's subsections return their own names as the result:

Screenshot from 2021-07-08 14-15-32
Screenshot from 2021-07-08 14-15-36
Screenshot from 2021-07-08 14-15-39

Search for the Launcher should be fixed with https://github.com/pop-os/desktop-widget/pull/31 once it's fixed, but I don't think that will help for the search within Settings.

Regarding https://github.com/pop-os/beta/issues/152, if I already have another desktop-widget page selected (like Dock), then `Change Background...` does take me to the Background page; but if I have a different Settings page selected (like Bluetooth), then `Change Background...` still brings me to the General page instead of the Background page.

**Comment by mmstick** [comment]
This and the other PR make the panels searchable in the launcher. It wouldn't yet work inside settings itself.

**Review by jackpot51 — APPROVED** [review]

**Comment by bflanagin** [comment]
From the launcher
Working: Tiling,Dock,Workspaces,Appearance, Cosmic

Mostly working: Background

Notes: Using the keywords: desktop,screens,wallpaper in the launcher displays Desktop (linked to Background), which is desirable if a little confusing, where as the keyword "background" displays all available options in the Desktop settings widget, instead of just the Background and possibly Desktop items. Screenshot for reference: 
Screenshot from 2021-07-13 11-12-12

Also there is a small disconnect between using the word Cosmic to get to the Desktop->General view when we call the section "Desktop" in GCC. This is made even more confusing in conjunction with how the launcher displays "Desktop" (which goes to Backgrounds) when you search for Workspaces,or Dock and not Cosmic. I imagine removing the Desktop option from the search results will fix the latter, but I'm not sure what the best option is for the former. Would it be against the grain to change the top level menu item from Desktop to Cosmic?

**Comment by mmstick** [comment]
We can change Desktop, but that would be in gnome-control-center, since that is where that desktop entry presides.

**Comment by bflanagin** [comment]
I'm cool with keeping it Cosmic for now if it makes merging this PR easier. The only thing that really stands out as "unintended behavior" is the background keyword displaying every option (as mentioned above.) ~I don't know how trivial the change is, but at the moment its the only blocker.~

**Comment by bflanagin** [comment]
Looking at the code here and in https://github.com/pop-os/desktop-widget/pull/31/files I realize the issue with the "background" keyword isn't directly connected with either PR and have created an issue for it. I'll create an issue about the naming miss match as well.

**Comment by ids1024** [comment]
I believe this is superseded by https://github.com/pop-os/gnome-control-center/pull/210. Closing.

**Pull request closed without merging**
