### PR TITLE
feat: Add analytics-panel

### PR DESCRIPTION
**Pull request by mmstick**
Requires analytics-panel repository to be manually built

### CODE REVIEW

**Comment by jackpot51** [comment]
@mmstick any updates to this?

**Comment by mmstick** [comment]
Waiting until HP Vendor is ready for integration with analytics-panel

**Comment by ids1024** [comment]
It should be possible to add a dependency on https://github.com/pop-os/hp-vendor/tree/master_jammy/hp-vendor-client to perform operations here. We'll want to improve how the API there handles some types of errors, and think about what the polkit prompts should look like.

**Comment by ids1024** [comment]
I guess this also needs to be updated and reopened against `master_jammy`.

**Comment by ids1024** [comment]
Closing in favor of https://github.com/pop-os/gnome-control-center/pull/219, which updates this to apply to `master_jammy`.

**Pull request closed without merging**
