### PR TITLE
focal: Add a patch for CcSearchLocationsDialog issue

### LINKED ISSUE #149: Changing search location options in Settings leads to a Segfault
**Distribution (run `cat /etc/os-release`):**
PopOs 20.10
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
PopOs Settings, supposedly newest (everything updated from apt and pop_shop)

**Issue/Bug Description:**
Changing search location options in Settings leads to a Segfault

**Steps to reproduce (if you know):**
Go to Settings-Search-Search_Locations, toggle any switch; 
The settings app will crash, and Journelctl shows segfault, see below; 

**Expected behavior:**
It should not crash with segfault...

**Other Notes:**
Journelctl log: 
...
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_new_for_commandline_arg: assertion 'arg != NULL' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh gnome-control-c[291373]: g_file_get_path: assertion 'G_IS_FILE (file)' failed
Feb 15 19:41:41 dt-ruizhezh kernel: gnome-control-c[291373]: segfault at 7ffe8fc24e58 ip 00007f49458e3521 sp 00007ffe8fc24e50 error 6 in libgio-2.0.so.0.6600.1[7f49457da000+119000]
Feb 15 19:41:41 dt-ruizhezh kernel: Code: 0e ff ff ff 0f 1f 44 00 00 f3 0f 1e fa 41 57 41 56 41 55 41 54 55 53 48 81 ec 00 10 00 00 48 83 0c 24 00 48 81 ec 88 02 00 00 <89> 4c 24 08 49 89 d4 49 89 ff 49 89 f5 4c 89 44 24 10 4c 89 cd 64

### PR DESCRIPTION
**Pull request by ids1024**
Fixes https://github.com/pop-os/gnome-control-center/issues/149

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
Confirmed this fixes the crash reported in https://github.com/pop-os/gnome-control-center/pull/150 on a Focal machine. These options don't seem to actually take effect in the Activities overview search results like the Search page's description would indicate, but that is not a regression (this may have to do with how Tracker is indexing and storing the results.)

While directories are hidden from the list when they're set to `$HOME` using `user-dirs.dirs`, those directories will stay in the `org.freedesktop.Tracker.Miner.Files index-recursive-directories` gsetting if they were enabled before this change was made. If they were disabled before this change was made, they won't be listed in that gsetting. Knowing this, it seems like maybe the option should still be displayed for the directories configured as `$HOME`, rather than being hidden.

@ids1024 Thoughts on if this is actually an issue? If we're changing from `get_user_special_dir_if_not_home` to `g_get_user_special_dir`, judging just from what those functions are called and the [description](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-user-special-dir) of the new function being used, I would expect the on/off switches to still show up for items that are set to `$HOME`, so the option to index them doesn't get stuck on.

**Comment by jacobgkau** [comment]
Actually, I see that if I set one of the special directories to any other directory, I get a custom on/off switch for that directory:

custom

In this example, I set `XDG_PICTURES_DIR` to `$HOME/Pictures-Custom`, and enabling/disabling the `Pictures-Custom` switch adds/removes `&PICTURES` to/from the gsetting. So maybe this is a separate issue where the `Home` on/off switch should control any of the directories set to `$HOME` in the gsetting. (It seems like duplicates aren't handled well; if I set `XDG_VIDEOS_DIR` to also point to `$HOME/Pictures-Custom`, I only get a single on/off switch, it only controls `&PICTURES`, `&VIDEOS` is stuck on in the gsetting, and I start getting `g_file_equal: assertion 'G_IS_FILE (file1)' failed` messages again.)

**Comment by ids1024** [comment]
> those directories will stay in the org.freedesktop.Tracker.Miner.Files index-recursive-directories gsetting if they were enabled before this change was made.

Hm, that does seem like a bug.

> judging just from what those functions are called and the description of the new function being used, I would expect the on/off switches to still show up for items that are set to $HOME, so the option to index them doesn't get stuck on.

The part of the code changed here isn't the part that determines whether or not they are shown.

So I think that's a bug that already existed, albeit somewhat hidden by the fact g-c-c could segfault before you could see how it behaves.

**Review by jacobgkau — APPROVED** [review]
> So I think that's a bug that already existed, albeit somewhat hidden by the fact g-c-c could segfault before you could see how it behaves.

To that point, I suppose these settings were already getting stuck on before. Being able to change some of the settings, or at least not crashing, is better than crashing and not being able to change any of them.

Approving this here, and I've opened an issue upstream about the larger issue of handling duplicate user dirs: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/1265

**Pull request merged**
