### PR TITLE
impish: Emit `sidebar-activated` on when selection item in Desktop sidebar

### LINKED ISSUE #195: "Desktop" Settings Can't Be Accessed in Narrow View
image

### PR DESCRIPTION
**Pull request by ids1024**
Fixes https://github.com/pop-os/gnome-control-center/issues/195

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
This is working to make the Desktop panels accessible in a narrow view. I'm seeing a couple of quirks.

- If I go into a page, then go back to the list, clicking the title again doesn't bring me back into that page:

gcc-pr202-gif1

Double-clicking does bring me back in, but that feels inconsistent since I didn't need to double-click the first time.

- The Appearance page's theme switcher is cut off:

Screenshot from 2021-11-18 12-02-53

It is horizontally scrollable, but seems like maybe it should break vertically instead of looking like this? (None of the other Desktop pages have to horizontally scroll.)

**Comment by ids1024** [comment]
> If I go into a page, then go back to the list, clicking the title again doesn't bring me back into that page:

Good catch. Updated to use `row-activated` signal instead of `row-selected`, just like the Applications panel. Should work as expected now.

> It is horizontally scrollable, but seems like maybe it should break vertically instead of looking like this?

Sounds good to me. See https://github.com/pop-os/theme-switcher/pull/29 and https://github.com/pop-os/desktop-widget/pull/73.

Since that's used as a shared library, that can be reviewed separately and doesn't block this PR, so this should be good now.

**Review by mmstick — APPROVED** [review]

**Comment by jacobgkau** [comment]
After navigating into any of the Desktop sub-pages and then back to the topmost page list, accessing the Desktop section again goes straight to the General page instead of the Desktop list:
desktop-page-selection

This does not happen with the Privacy section:
privacy-page-selection

**Review by jacobgkau — APPROVED** [review]
Because this is an improvement over current behavior, at @jackpot51's request, I've opened https://github.com/pop-os/gnome-control-center/issues/203 to track the remaining navigation issue and am approving this partial fix.

**Pull request merged**
