### PR TITLE
improv: Remove "Adjust for TV" setting

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by jacobgkau** [comment]
Can I ask for the rationale behind removing this setting? I know we have at least [one user](https://chat.pop-os.org/pop-os/pl/p8bwqsrb3iggdkidzmqjoodjfy) who's using it; I would assume not many people need it, but it's one of those things that would be pretty important for those who do.

**Comment by jacobgkau** [comment]
@jackpot51 informed me that the rationale (beyond low usage, since most TVs allow doing this in their settings instead of relying on software) is that the setting is hard-coded to underscan a specific amount, which may not be correct for all TVs: https://gitlab.gnome.org/GNOME/mutter/-/issues/1046

**Comment by jacobgkau** [comment]
I don't see a gsetting that controls this option (I think it might just save a property to monitors.xml). For X11, it looks like there may be two ways to achieve underscanning (an underscan property and a transform property) manually using xrandr: https://wiki.archlinux.org/title/Xrandr#Correction_of_overscan_tv_resolutions_via_the_underscan_property 

That should hopefully fill the gap for users who do use this feature. It sort of makes me wonder if hidpi-daemon could offer a similar option, although I'm not sure hidpi-daemon's future is certain with regards to Wayland/COSMIC.

**Comment by jacobgkau** [comment]
Regression testing is looking fine on this so far. The last thing we want to check is trying it out with a display/TV that used to show the option to make sure nothing wonky occurs (we don't have one of those in the lab, but someone on the team has one at home and will hopefully be able to check it tonight.)

**Comment by leviport** [comment]
I think I was mistaken about my old TV needing this setting. Whether or not the setting ever showed up before, I'm not seeing it now. Sorry for the confusion.

**Review by jacobgkau — APPROVED** [review]
We don't seem to have any display for testing that actually shows this setting without the patch. The panel is still working normally (with all expected settings visible/working) on unaffected hardware with the patch.

**Review by jackpot51 — APPROVED** [review]

**Comment by johnblommers** [comment]
The GNOME project has a reputation for removing features with each release.

By removing this feature GNOME developers are affirming this reputation.

**Comment by jackpot51** [comment]
GNOME didn't remove this feature, we did.

**Comment by jackpot51** [comment]
@johnblommers if you want more details on why the feature was removed, it boils down to it rarely working correctly. See the comments on https://www.reddit.com/r/pop_os/comments/tx4kf0/goodbye_pop_its_been_a_great_time/

**Comment by jackpot51** [comment]
If the feature is ever re-introduced, we would want it to support arbitrary underscan and overscan percentages rather than only supporting exactly 5% underscan.

**Pull request merged**
