### PR TITLE
Add HiDPI daemon toggles

### LINKED ISSUE #19: No HiDPI Daemon controls in 19.04
On the `Displays` page of gnome-control-center, there is no HiDPI daemon toggle/settings.

### PR DESCRIPTION
**Pull request by jackpot51**
This fixes #19

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by brs17** [comment]
I see that the second toggle option says: `Enable to render LoDPI displays at HiDPI resolution.`

In previous versions, the options are just `HiDPI` and `LoDPI`. While the new text above is more specific with what is actually happening, this wording maches the wording in the daemon notification. I'm not sure I like such an inconsistency (and it may be confusing to users).

Thoughts?

**Comment by jackpot51** [comment]
The previous wording was just `Mode` with `LoDPI` or `HiDPI` in a combo box. This said nothing about what the toggle did. Also, the code required to support a combo box is significantly more than the code required to support a switch. So I adjusted the wording to apply to what HiDPI mode entails when it is enabled. It renders the LoDPI displays at twice their resolution.

**Comment by brs17** [comment]
I agree that the notification does not really say what is going on, and I do think the consistency of using two switches is a good idea, however, I think improved consistency between the notification and the text in gnome control center is a necessity.

Screenshot from 2019-04-23 07-41-54

What do you think of changing the text in the notification from `Displays set to HiDPI Mode`/`Displays set to LoDPI Mode` to `Displays set to HiDPI Resolution`/`Displays set to LoDPI Resolution`?

**Comment by jackpot51** [comment]
Seeing the notification text, I don't think any change to the wording needs to be made

**Review by brs17 — APPROVED** [review]

**Pull request merged**
